language: node_js
node_js:
 - 17
cache:
 directories:
   - node_modules
script:
 - npm run test
 - npm run build
 - npm run start:prod
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: build
 on:
   branch: master